import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import starlight from "@astrojs/starlight";

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: "BlueBelt Dojo — AI SDLC Workshop",
      customCss: ["./src/styles/custom.css"],
      defaultLocale: "root",
      locales: {
        root: {
          label: "ไทย",
          lang: "th",
        },
        en: {
          label: "English",
          lang: "en",
        },
      },
      head: [
        {
          tag: "script",
          attrs: { defer: true, src: "/js/progress-tracker.js" },
        },
      ],
      sidebar: [
        {
          label: "Course",
          items: [{ slug: "workshop/overview" }],
        },
        {
          label: "Module 1: AI & LLM Foundations",
          collapsed: true,
          items: [
            { slug: "workshop/block-1-ai-tools" },
            { slug: "quests/quest-1-first-code" },
            { slug: "quests/quest-2-prompts" },
            { slug: "quests/quest-3-security" },
            { slug: "quests/quest-4-loops" },
            { slug: "quests/quest-5-project" },
            { slug: "quests/quest-6-multi-file" },
            { slug: "quests/quest-7-compare-tools" },
            { slug: "quests/quest-8-multi-step" },
            { slug: "quests/quest-9-domain-specific" },
            { slug: "quests/quest-10-fix-harden" },
            { slug: "quests/quest-11-security-architecture" },
            { slug: "quests/quest-12-generate-review-fix" },
          ],
        },
        {
          label: "Module 2: LLM Training",
          collapsed: true,
          items: [
            { slug: "quests/quest-14-rag-design" },
            { slug: "quests/quest-15-data" },
            { slug: "quests/quest-16-finetuning" },
            { slug: "quests/quest-17-dpo" },
            { slug: "quests/quest-18-sampling" },
            { slug: "quests/quest-19-chain" },
            { slug: "quests/quest-20-rag" },
            { slug: "quests/quest-21-semantic" },
            { slug: "quests/quest-22-hallucination" },
          ],
        },
        {
          label: "Module 3: SDLC Phases",
          collapsed: true,
          items: [
            { slug: "quests/quest-23-user" },
            { slug: "quests/quest-24-prd" },
            { slug: "quests/quest-25-adr" },
            { slug: "quests/quest-26-tech" },
            { slug: "quests/quest-27-risk" },
            { slug: "quests/quest-28-sprint" },
            { slug: "quests/quest-29-requirements" },
            { slug: "quests/quest-30-prompt" },
            { slug: "quests/quest-31-context" },
            { slug: "quests/quest-32-mcp" },
            { slug: "quests/quest-33-function" },
            { slug: "quests/quest-34-react" },
            { slug: "quests/quest-35-multi" },
            { slug: "quests/quest-36-code" },
            { slug: "quests/quest-37-intent" },
            { slug: "quests/quest-38-edge" },
            { slug: "quests/quest-39-test" },
            { slug: "quests/quest-40-mock" },
            { slug: "quests/quest-41-ci" },
            { slug: "quests/quest-42-regression" },
          ],
        },
        {
          label: "Module 4: Security & Deployment",
          collapsed: true,
          items: [
            { slug: "quests/quest-43-sql-injection-spotter" },
            { slug: "quests/quest-44-secret-scanner" },
            { slug: "quests/quest-45-input-validator" },
            { slug: "quests/quest-46-auth-system" },
            { slug: "quests/quest-47-prompt-injection" },
            { slug: "quests/quest-48-security-arch" },
            { slug: "quests/quest-49-dependency-auditor" },
            { slug: "quests/quest-50-ai-review-policy" },
            { slug: "quests/quest-51-ip-risk-analyzer" },
            { slug: "quests/quest-52-audit-trail" },
            { slug: "quests/quest-53-bias-detector" },
            { slug: "quests/quest-54-ai-usage-policy" },
            { slug: "quests/quest-55-compliance-checker" },
            { slug: "quests/quest-56-dockerfile-generator" },
            { slug: "quests/quest-57-iac-generator" },
            { slug: "quests/quest-58-deploy-pipeline" },
            { slug: "quests/quest-59-monitoring-dashboard" },
            { slug: "quests/quest-60-llm-observability" },
            { slug: "quests/quest-61-cost-optimizer" },
            { slug: "quests/quest-62-rollback-strategist" },
          ],
        },
        {
          label: "Module 5: Advanced Patterns",
          collapsed: true,
          items: [
            { slug: "quests/quest-63-agent-loop" },
            { slug: "quests/quest-64-tool-registry" },
            { slug: "quests/quest-65-agent-debate" },
            { slug: "quests/quest-66-agent-hierarchy" },
            { slug: "quests/quest-67-self-reflecting" },
            { slug: "quests/quest-68-llm-evaluator" },
            { slug: "quests/quest-69-semantic-cache" },
            { slug: "quests/quest-70-prompt-versioning" },
            { slug: "quests/quest-71-rate-limiter" },
            { slug: "quests/quest-72-prod-readiness" },
          ],
        },
        {
          label: "Module 6: Prompt Engineering",
          collapsed: true,
          items: [
            { slug: "quests/quest-73-role-prompts" },
            { slug: "quests/quest-74-few-shot" },
            { slug: "quests/quest-75-chain-density" },
            { slug: "quests/quest-76-structured-output" },
            { slug: "quests/quest-77-prompt-chainer" },
            { slug: "quests/quest-78-context-engineering" },
            { slug: "quests/quest-79-meta-prompt" },
            { slug: "quests/quest-80-injection-tester" },
            { slug: "quests/quest-81-prompt-eval" },
            { slug: "quests/quest-82-prompt-porter" },
          ],
        },
        {
          label: "Module 7: Review & Docs",
          collapsed: true,
          items: [
            { slug: "quests/quest-83-automated-pr-reviewer" },
            { slug: "quests/quest-84-code-smell-detector" },
            { slug: "quests/quest-85-security-review" },
            { slug: "quests/quest-86-performance-review" },
            { slug: "quests/quest-87-review-quality" },
            { slug: "quests/quest-88-docstring-generator" },
            { slug: "quests/quest-89-readme-generator" },
            { slug: "quests/quest-90-api-doc-generator" },
            { slug: "quests/quest-91-changelog-generator" },
            { slug: "quests/quest-92-onboarding-doc" },
          ],
        },
        {
          label: "Module 8: Refactoring",
          collapsed: true,
          items: [
            { slug: "quests/quest-93-code-simplifier" },
            { slug: "quests/quest-94-dead-code" },
            { slug: "quests/quest-95-design-pattern" },
            { slug: "quests/quest-96-type-migration" },
            { slug: "quests/quest-97-legacy-modernizer" },
            { slug: "quests/quest-98-api-migration" },
            { slug: "quests/quest-99-db-migration" },
            { slug: "quests/quest-100-framework-migration" },
            { slug: "quests/quest-101-monolith-splitter" },
            { slug: "quests/quest-102-test-migration" },
          ],
        },
        {
          label: "Module 9: Ethics & Multimodal",
          collapsed: true,
          items: [
            { slug: "quests/quest-103-bias-auditor" },
            { slug: "quests/quest-104-pii-redactor" },
            { slug: "quests/quest-105-ethical-framework" },
            { slug: "quests/quest-106-accessibility-checker" },
            { slug: "quests/quest-107-image-prompt" },
            { slug: "quests/quest-108-multimodal-processor" },
            { slug: "quests/quest-109-voice-to-code" },
            { slug: "quests/quest-110-multimodal-rag" },
          ],
        },
        {
          label: "Module 10: Integration",
          collapsed: true,
          items: [
            { slug: "quests/quest-111-e2e-pipeline" },
            { slug: "quests/quest-112-workflow-orchestrator" },
            { slug: "quests/quest-113-incident-responder" },
            { slug: "quests/quest-114-feature-flags" },
            { slug: "quests/quest-115-copilot-analysis" },
            { slug: "quests/quest-116-enterprise-adoption" },
            { slug: "quests/quest-117-ai-roi" },
            { slug: "quests/quest-118-governance-framework" },
          ],
        },
        {
          label: "Module 11: Git & GitHub",
          collapsed: true,
          items: [
            { slug: "quests/quest-119-git-repo-setup" },
            { slug: "quests/quest-120-branching-strategy" },
            { slug: "quests/quest-121-commit-message" },
            { slug: "quests/quest-122-history-analyzer" },
            { slug: "quests/quest-123-rebase-simulator" },
            { slug: "quests/quest-124-issue-creator" },
            { slug: "quests/quest-125-pr-description" },
            { slug: "quests/quest-126-project-board" },
            { slug: "quests/quest-127-code-review-sim" },
            { slug: "quests/quest-128-cicd-pipeline" },
          ],
        },
        {
          label: "Module 12: Cloudflare Deployment",
          collapsed: true,
          items: [
            { slug: "quests/quest-129-pages-deploy" },
            { slug: "quests/quest-130-function-router" },
            { slug: "quests/quest-131-worker-api" },
            { slug: "quests/quest-132-worker-env-config" },
            { slug: "quests/quest-133-kv-manager" },
            { slug: "quests/quest-134-d1-migrator" },
            { slug: "quests/quest-135-r2-uploader" },
            { slug: "quests/quest-136-fullstack-deploy" },
          ],
        },
        {
          label: "Capstones",
          items: [
            { slug: "capstones/capstone-1-api-service" },
            { slug: "capstones/capstone-2-multi-agent" },
            { slug: "capstones/capstone-3-production-ai" },
          ],
        },
        {
          label: "Account",
          items: [
            { label: "Dashboard", link: "/dashboard" },
            { label: "Community", link: "/community" },
            { label: "Pricing", link: "/pricing" },
          ],
        },
        {
          label: "Reference",
          items: [
            { slug: "reference/setup-guide" },
            { slug: "reference/github-copilot" },
            { slug: "reference/claude-code" },
            { slug: "reference/code-rabbit" },
            { slug: "reference/matt-skills" },
            { slug: "reference/execution-skills" },
            { slug: "reference/goal-system" },
          ],
        },
      ],
    }),
    tailwind(),
  ],
  site: "https://bluebeltdojo.ai",
});
